// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervacijaStolaApp.Models.Data;

#nullable disable

namespace RezervacijaStolaApp.Migrations
{
    [DbContext(typeof(DeskReservationDataContext))]
    [Migration("20260902201615_EditDeskTableAddWoorkToolsId")]
    partial class EditDeskTableAddWoorkToolsId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeskNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomFloorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoorkToolsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomFloorId");

                    b.ToTable("Desks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeskNumber = 124,
                            RoomFloorId = 1,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 2,
                            DeskNumber = 224,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 3,
                            DeskNumber = 98,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 4,
                            DeskNumber = 13,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 5,
                            DeskNumber = 295,
                            RoomFloorId = 4,
                            WoorkToolsId = 0
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DeskId", "ReservationDate")
                        .IsUnique();

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeskId = 1,
                            ReservationDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeskId = 2,
                            ReservationDate = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DeskId = 3,
                            ReservationDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DeskId = 4,
                            ReservationDate = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DeskId = 2,
                            ReservationDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            DeskId = 3,
                            ReservationDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            DeskId = 1,
                            ReservationDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            DeskId = 4,
                            ReservationDate = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            DeskId = 4,
                            ReservationDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            DeskId = 3,
                            ReservationDate = new DateTime(2026, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            DeskId = 2,
                            ReservationDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            DeskId = 5,
                            ReservationDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 13,
                            DeskId = 5,
                            ReservationDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.RoomFloor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorShort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomFloor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Floor = "-1",
                            FloorDescription = "Suteren",
                            FloorShort = "S"
                        },
                        new
                        {
                            Id = 2,
                            Floor = "0",
                            FloorDescription = "Prizemlje",
                            FloorShort = "P"
                        },
                        new
                        {
                            Id = 3,
                            Floor = "1",
                            FloorDescription = "Prvi kat",
                            FloorShort = "K1"
                        },
                        new
                        {
                            Id = 4,
                            Floor = "2",
                            FloorDescription = "Drugi kat",
                            FloorShort = "K2"
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailAdress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellPhoneNumber = "0993855267",
                            MailAdress = "mabarbic22@gmail.com",
                            Name = "Marko",
                            Surname = "Barbić"
                        },
                        new
                        {
                            Id = 2,
                            CellPhoneNumber = "0993456755",
                            MailAdress = "nibarbic22@gmail.com",
                            Name = "Nikolina",
                            Surname = "Barbić"
                        },
                        new
                        {
                            Id = 3,
                            CellPhoneNumber = "0912675098",
                            MailAdress = "tomi12@gmail.com",
                            Name = "Tomislav",
                            Surname = "Marković"
                        },
                        new
                        {
                            Id = 4,
                            CellPhoneNumber = "0923456123",
                            MailAdress = "josip.ninic@vsite.hr",
                            Name = "Josip",
                            Surname = "Ninić"
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.WorkTools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeskId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Desktop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DockingStation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Keyboard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mouse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeskId")
                        .IsUnique();

                    b.ToTable("WorkTools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeskId = 1,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 2,
                            DeskId = 2,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 3,
                            DeskId = 3,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 4,
                            DeskId = 4,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.RoomFloor", "RoomFloor")
                        .WithMany()
                        .HasForeignKey("RoomFloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomFloor");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Reservation", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.Desk", "Desk")
                        .WithMany("ListOfReservations")
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervacijaStolaApp.Models.Data.User", "User")
                        .WithMany("UserReservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.WorkTools", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.Desk", null)
                        .WithOne("WorkTools")
                        .HasForeignKey("RezervacijaStolaApp.Models.Data.WorkTools", "DeskId");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.Navigation("ListOfReservations");

                    b.Navigation("WorkTools")
                        .IsRequired();
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.User", b =>
                {
                    b.Navigation("UserReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
