// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervacijaStolaApp.Models.Data;

#nullable disable

namespace RezervacijaStolaApp.Migrations
{
    [DbContext(typeof(DeskReservationDataContext))]
    [Migration("20260828142440_CreateInitialTablesAndRequiredFields")]
    partial class CreateInitialTablesAndRequiredFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeskNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Desks");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeskId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailAdress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.WorkTools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeskId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Desktop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DockingStation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Keyboard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mouse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeskId");

                    b.ToTable("WorkTools");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Reservation", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.Desk", "Desk")
                        .WithMany("ListOfReservations")
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervacijaStolaApp.Models.Data.User", "User")
                        .WithMany("UserReservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.WorkTools", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.Desk", null)
                        .WithMany("WorkTools")
                        .HasForeignKey("DeskId");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.Navigation("ListOfReservations");

                    b.Navigation("WorkTools");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.User", b =>
                {
                    b.Navigation("UserReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
