// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervacijaStolaApp.Models.Data;

#nullable disable

namespace RezervacijaStolaApp.Migrations
{
    [DbContext(typeof(DeskReservationDataContext))]
    [Migration("20260904120210_AddDataaToReservationsTable")]
    partial class AddDataaToReservationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeskNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomFloorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoorkToolsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomFloorId");

                    b.ToTable("Desks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeskNumber = 1,
                            RoomFloorId = 1,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 2,
                            DeskNumber = 2,
                            RoomFloorId = 1,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 3,
                            DeskNumber = 3,
                            RoomFloorId = 1,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 4,
                            DeskNumber = 4,
                            RoomFloorId = 1,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 5,
                            DeskNumber = 5,
                            RoomFloorId = 1,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 6,
                            DeskNumber = 6,
                            RoomFloorId = 1,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 7,
                            DeskNumber = 7,
                            RoomFloorId = 1,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 8,
                            DeskNumber = 8,
                            RoomFloorId = 1,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 9,
                            DeskNumber = 9,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 10,
                            DeskNumber = 10,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 11,
                            DeskNumber = 11,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 12,
                            DeskNumber = 12,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 13,
                            DeskNumber = 13,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 14,
                            DeskNumber = 14,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 15,
                            DeskNumber = 15,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 16,
                            DeskNumber = 16,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 17,
                            DeskNumber = 17,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 18,
                            DeskNumber = 18,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 19,
                            DeskNumber = 19,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 20,
                            DeskNumber = 20,
                            RoomFloorId = 2,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 21,
                            DeskNumber = 21,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 22,
                            DeskNumber = 22,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 23,
                            DeskNumber = 23,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 24,
                            DeskNumber = 24,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 25,
                            DeskNumber = 25,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 26,
                            DeskNumber = 26,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 27,
                            DeskNumber = 27,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 28,
                            DeskNumber = 28,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 29,
                            DeskNumber = 29,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 30,
                            DeskNumber = 30,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 31,
                            DeskNumber = 31,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 32,
                            DeskNumber = 32,
                            RoomFloorId = 3,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 33,
                            DeskNumber = 33,
                            RoomFloorId = 4,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 34,
                            DeskNumber = 34,
                            RoomFloorId = 4,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 35,
                            DeskNumber = 35,
                            RoomFloorId = 4,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 36,
                            DeskNumber = 36,
                            RoomFloorId = 4,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 37,
                            DeskNumber = 37,
                            RoomFloorId = 4,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 38,
                            DeskNumber = 38,
                            RoomFloorId = 4,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 39,
                            DeskNumber = 39,
                            RoomFloorId = 4,
                            WoorkToolsId = 0
                        },
                        new
                        {
                            Id = 40,
                            DeskNumber = 40,
                            RoomFloorId = 4,
                            WoorkToolsId = 0
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DeskId", "ReservationDate")
                        .IsUnique();

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeskId = 1,
                            ReservationDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeskId = 2,
                            ReservationDate = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DeskId = 3,
                            ReservationDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DeskId = 4,
                            ReservationDate = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DeskId = 23,
                            ReservationDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DeskId = 32,
                            ReservationDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DeskId = 11,
                            ReservationDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DeskId = 12,
                            ReservationDate = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DeskId = 18,
                            ReservationDate = new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DeskId = 21,
                            ReservationDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        },
                        new
                        {
                            Id = 11,
                            DeskId = 22,
                            ReservationDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            DeskId = 40,
                            ReservationDate = new DateTime(2026, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            DeskId = 26,
                            ReservationDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9
                        },
                        new
                        {
                            Id = 14,
                            DeskId = 35,
                            ReservationDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            DeskId = 7,
                            ReservationDate = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            DeskId = 33,
                            ReservationDate = new DateTime(2026, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            DeskId = 12,
                            ReservationDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9
                        },
                        new
                        {
                            Id = 18,
                            DeskId = 4,
                            ReservationDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        },
                        new
                        {
                            Id = 19,
                            DeskId = 9,
                            ReservationDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            DeskId = 24,
                            ReservationDate = new DateTime(2026, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.RoomFloor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomFloor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Floor = "-1",
                            FloorDescription = "Suteren"
                        },
                        new
                        {
                            Id = 2,
                            Floor = "0",
                            FloorDescription = "Prizemlje"
                        },
                        new
                        {
                            Id = 3,
                            Floor = "1",
                            FloorDescription = "Prvi kat"
                        },
                        new
                        {
                            Id = 4,
                            Floor = "2",
                            FloorDescription = "Drugi kat"
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailAdress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellPhoneNumber = "0993855267",
                            MailAdress = "mabarbic22@gmail.com",
                            Name = "Marko",
                            Surname = "Barbić"
                        },
                        new
                        {
                            Id = 2,
                            CellPhoneNumber = "0993456755",
                            MailAdress = "nibirac@gmail.com",
                            Name = "Nikolina",
                            Surname = "Birač"
                        },
                        new
                        {
                            Id = 3,
                            CellPhoneNumber = "0912675098",
                            MailAdress = "tomi12@gmail.com",
                            Name = "Tomislav",
                            Surname = "Marković"
                        },
                        new
                        {
                            Id = 4,
                            CellPhoneNumber = "0923456123",
                            MailAdress = "josip.ninic@vsite.hr",
                            Name = "Josip",
                            Surname = "Ninić"
                        },
                        new
                        {
                            Id = 5,
                            CellPhoneNumber = "092344573",
                            MailAdress = "nikolanik@vsite.hr",
                            Name = "Nikola",
                            Surname = "Nikolić"
                        },
                        new
                        {
                            Id = 6,
                            CellPhoneNumber = "0923456123",
                            MailAdress = "astanic@gmail.com",
                            Name = "Andrej",
                            Surname = "Stanić"
                        },
                        new
                        {
                            Id = 7,
                            CellPhoneNumber = "0923456723",
                            MailAdress = "monijosipov@gmail.com",
                            Name = "Monika",
                            Surname = "Josipović"
                        },
                        new
                        {
                            Id = 8,
                            CellPhoneNumber = "092788823",
                            MailAdress = "juricjure@gmail.com",
                            Name = "Jure",
                            Surname = "Jurić"
                        },
                        new
                        {
                            Id = 9,
                            CellPhoneNumber = "098157899",
                            MailAdress = "tihica.glasn@gmail.com",
                            Name = "Tihomir",
                            Surname = "Glasnović"
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.WorkTools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeskId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Desktop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DockingStation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Keyboard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mouse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeskId")
                        .IsUnique();

                    b.ToTable("WorkTools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeskId = 1,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 2,
                            DeskId = 2,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 3,
                            DeskId = 3,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 4,
                            DeskId = 4,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        },
                        new
                        {
                            Id = 5,
                            DeskId = 5,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 6,
                            DeskId = 6,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 7,
                            DeskId = 7,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 8,
                            DeskId = 8,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        },
                        new
                        {
                            Id = 9,
                            DeskId = 9,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 10,
                            DeskId = 10,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 11,
                            DeskId = 11,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 12,
                            DeskId = 12,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        },
                        new
                        {
                            Id = 13,
                            DeskId = 13,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 14,
                            DeskId = 14,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 15,
                            DeskId = 15,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 16,
                            DeskId = 16,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        },
                        new
                        {
                            Id = 17,
                            DeskId = 17,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 18,
                            DeskId = 18,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 19,
                            DeskId = 19,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 20,
                            DeskId = 20,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        },
                        new
                        {
                            Id = 21,
                            DeskId = 21,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 22,
                            DeskId = 22,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 23,
                            DeskId = 23,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 24,
                            DeskId = 24,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        },
                        new
                        {
                            Id = 25,
                            DeskId = 25,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 26,
                            DeskId = 26,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 27,
                            DeskId = 27,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 28,
                            DeskId = 28,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        },
                        new
                        {
                            Id = 29,
                            DeskId = 29,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 30,
                            DeskId = 30,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 31,
                            DeskId = 31,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 32,
                            DeskId = 32,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        },
                        new
                        {
                            Id = 33,
                            DeskId = 33,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 34,
                            DeskId = 34,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 35,
                            DeskId = 35,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 36,
                            DeskId = 36,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        },
                        new
                        {
                            Id = 37,
                            DeskId = 37,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 38,
                            DeskId = 38,
                            Desktop = false,
                            DockingStation = false,
                            Keyboard = false,
                            Mouse = false
                        },
                        new
                        {
                            Id = 39,
                            DeskId = 39,
                            Desktop = true,
                            DockingStation = true,
                            Keyboard = false,
                            Mouse = true
                        },
                        new
                        {
                            Id = 40,
                            DeskId = 40,
                            Desktop = true,
                            DockingStation = false,
                            Keyboard = true,
                            Mouse = true
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.RoomFloor", "RoomFloor")
                        .WithMany()
                        .HasForeignKey("RoomFloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomFloor");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Reservation", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.Desk", "Desk")
                        .WithMany("ListOfReservations")
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervacijaStolaApp.Models.Data.User", "User")
                        .WithMany("UserReservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.WorkTools", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.Desk", null)
                        .WithOne("WorkTools")
                        .HasForeignKey("RezervacijaStolaApp.Models.Data.WorkTools", "DeskId");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.Navigation("ListOfReservations");

                    b.Navigation("WorkTools")
                        .IsRequired();
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.User", b =>
                {
                    b.Navigation("UserReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
