// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervacijaStolaApp.Models.Data;

#nullable disable

namespace RezervacijaStolaApp.Migrations
{
    [DbContext(typeof(DeskReservationDataContext))]
    [Migration("20260829100809_AddInitialDesk")]
    partial class AddInitialDesk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeskNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Desks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeskNumber = 124,
                            Room = "1"
                        },
                        new
                        {
                            Id = 2,
                            DeskNumber = 224,
                            Room = "S11"
                        },
                        new
                        {
                            Id = 3,
                            DeskNumber = 98,
                            Room = "2"
                        },
                        new
                        {
                            Id = 4,
                            DeskNumber = 13,
                            Room = "7"
                        },
                        new
                        {
                            Id = 5,
                            DeskNumber = 295,
                            Room = "S2"
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DeskId", "ReservationDate")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailAdress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellPhoneNumber = "0993855267",
                            MailAdress = "mabarbic22@gmail.com",
                            Name = "Marko",
                            Surname = "Barbić"
                        },
                        new
                        {
                            Id = 2,
                            CellPhoneNumber = "0993456755",
                            MailAdress = "nibarbic22@gmail.com",
                            Name = "Nikolina",
                            Surname = "Barbić"
                        },
                        new
                        {
                            Id = 3,
                            CellPhoneNumber = "0912675098",
                            MailAdress = "tomi12@gmail.com",
                            Name = "Tomislav",
                            Surname = "Marković"
                        },
                        new
                        {
                            Id = 4,
                            CellPhoneNumber = "0923456123",
                            MailAdress = "josip.ninic@vsite.hr",
                            Name = "Josip",
                            Surname = "Ninić"
                        });
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.WorkTools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeskId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Desktop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DockingStation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Keyboard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mouse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeskId");

                    b.ToTable("WorkTools");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Reservation", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.Desk", "Desk")
                        .WithMany("ListOfReservations")
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervacijaStolaApp.Models.Data.User", "User")
                        .WithMany("UserReservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.WorkTools", b =>
                {
                    b.HasOne("RezervacijaStolaApp.Models.Data.Desk", null)
                        .WithMany("WorkTools")
                        .HasForeignKey("DeskId");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.Desk", b =>
                {
                    b.Navigation("ListOfReservations");

                    b.Navigation("WorkTools");
                });

            modelBuilder.Entity("RezervacijaStolaApp.Models.Data.User", b =>
                {
                    b.Navigation("UserReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
